// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/Avatar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VCamera: typeof import('./components/VCamera.vue')['default']
    VClock: typeof import('./components/VClock.vue')['default']
    VLogin: typeof import('./components/VLogin.vue')['default']
    VNotification: typeof import('./components/VNotification.vue')['default']
    VNotifications: typeof import('./components/VNotifications.vue')['default']
    VNotify: typeof import('./components/VNotify.vue')['default']
    VShareScreen: typeof import('./components/VShareScreen.vue')['default']
    VSideBar: typeof import('./components/VSideBar.vue')['default']
    VYoutube: typeof import('./components/VYoutube.vue')['default']
  }
}
